// Code generated by protoc-gen-go. DO NOT EDIT.
// source: main.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	main.proto

It has these top-level messages:
	CodisUserProfileUid
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CodisUserProfileUid struct {
	Ctseries            []int32                              `protobuf:"varint,1,rep,name=Ctseries" json:"Ctseries,omitempty"`
	Ctforums            []int32                              `protobuf:"varint,2,rep,name=Ctforums" json:"Ctforums,omitempty"`
	Bsforums            []int32                              `protobuf:"varint,3,rep,name=Bsforums" json:"Bsforums,omitempty"`
	Idfcars             []*CodisUserProfileUid_SigCarMessage `protobuf:"bytes,4,rep,name=Idfcars" json:"Idfcars,omitempty"`
	Poreforums          []int32                              `protobuf:"varint,5,rep,name=Poreforums" json:"Poreforums,omitempty"`
	UPurPow             *CodisUserProfileUid_PurPowInfo      `protobuf:"bytes,6,opt,name=UPurPow" json:"UPurPow,omitempty"`
	InterestSeriesList  []int32                              `protobuf:"varint,7,rep,name=InterestSeriesList" json:"InterestSeriesList,omitempty"`
	Uid                 *string                              `protobuf:"bytes,8,opt,name=Uid" json:"Uid,omitempty"`
	InterestAuthors     []int64                              `protobuf:"varint,9,rep,name=InterestAuthors" json:"InterestAuthors,omitempty"`
	InterestYoujiAuthor []int64                              `protobuf:"varint,10,rep,name=InterestYoujiAuthor" json:"InterestYoujiAuthor,omitempty"`
	XXX_unrecognized    []byte                               `json:"-"`
}

func (m *CodisUserProfileUid) Reset()                    { *m = CodisUserProfileUid{} }
func (m *CodisUserProfileUid) String() string            { return proto.CompactTextString(m) }
func (*CodisUserProfileUid) ProtoMessage()               {}
func (*CodisUserProfileUid) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CodisUserProfileUid) GetCtseries() []int32 {
	if m != nil {
		return m.Ctseries
	}
	return nil
}

func (m *CodisUserProfileUid) GetCtforums() []int32 {
	if m != nil {
		return m.Ctforums
	}
	return nil
}

func (m *CodisUserProfileUid) GetBsforums() []int32 {
	if m != nil {
		return m.Bsforums
	}
	return nil
}

func (m *CodisUserProfileUid) GetIdfcars() []*CodisUserProfileUid_SigCarMessage {
	if m != nil {
		return m.Idfcars
	}
	return nil
}

func (m *CodisUserProfileUid) GetPoreforums() []int32 {
	if m != nil {
		return m.Poreforums
	}
	return nil
}

func (m *CodisUserProfileUid) GetUPurPow() *CodisUserProfileUid_PurPowInfo {
	if m != nil {
		return m.UPurPow
	}
	return nil
}

func (m *CodisUserProfileUid) GetInterestSeriesList() []int32 {
	if m != nil {
		return m.InterestSeriesList
	}
	return nil
}

func (m *CodisUserProfileUid) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *CodisUserProfileUid) GetInterestAuthors() []int64 {
	if m != nil {
		return m.InterestAuthors
	}
	return nil
}

func (m *CodisUserProfileUid) GetInterestYoujiAuthor() []int64 {
	if m != nil {
		return m.InterestYoujiAuthor
	}
	return nil
}

type CodisUserProfileUid_SigCarMessage struct {
	SpecId           *int32  `protobuf:"varint,1,opt,name=Spec_id" json:"Spec_id,omitempty"`
	BrandId          *int32  `protobuf:"varint,2,opt,name=Brand_id" json:"Brand_id,omitempty"`
	FactoryId        *int32  `protobuf:"varint,3,opt,name=Factory_id" json:"Factory_id,omitempty"`
	BuyDate          *string `protobuf:"bytes,4,opt,name=Buy_date" json:"Buy_date,omitempty"`
	IsDriving        *int32  `protobuf:"varint,5,opt,name=Is_driving" json:"Is_driving,omitempty"`
	SeriesId         *int32  `protobuf:"varint,6,opt,name=Series_id" json:"Series_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CodisUserProfileUid_SigCarMessage) Reset()         { *m = CodisUserProfileUid_SigCarMessage{} }
func (m *CodisUserProfileUid_SigCarMessage) String() string { return proto.CompactTextString(m) }
func (*CodisUserProfileUid_SigCarMessage) ProtoMessage()    {}
func (*CodisUserProfileUid_SigCarMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

func (m *CodisUserProfileUid_SigCarMessage) GetSpecId() int32 {
	if m != nil && m.SpecId != nil {
		return *m.SpecId
	}
	return 0
}

func (m *CodisUserProfileUid_SigCarMessage) GetBrandId() int32 {
	if m != nil && m.BrandId != nil {
		return *m.BrandId
	}
	return 0
}

func (m *CodisUserProfileUid_SigCarMessage) GetFactoryId() int32 {
	if m != nil && m.FactoryId != nil {
		return *m.FactoryId
	}
	return 0
}

func (m *CodisUserProfileUid_SigCarMessage) GetBuyDate() string {
	if m != nil && m.BuyDate != nil {
		return *m.BuyDate
	}
	return ""
}

func (m *CodisUserProfileUid_SigCarMessage) GetIsDriving() int32 {
	if m != nil && m.IsDriving != nil {
		return *m.IsDriving
	}
	return 0
}

func (m *CodisUserProfileUid_SigCarMessage) GetSeriesId() int32 {
	if m != nil && m.SeriesId != nil {
		return *m.SeriesId
	}
	return 0
}

type CodisUserProfileUid_PurPowInfo struct {
	MinPrice         *int32 `protobuf:"varint,1,opt,name=MinPrice" json:"MinPrice,omitempty"`
	MaxPrice         *int32 `protobuf:"varint,2,opt,name=MaxPrice" json:"MaxPrice,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CodisUserProfileUid_PurPowInfo) Reset()         { *m = CodisUserProfileUid_PurPowInfo{} }
func (m *CodisUserProfileUid_PurPowInfo) String() string { return proto.CompactTextString(m) }
func (*CodisUserProfileUid_PurPowInfo) ProtoMessage()    {}
func (*CodisUserProfileUid_PurPowInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 1}
}

func (m *CodisUserProfileUid_PurPowInfo) GetMinPrice() int32 {
	if m != nil && m.MinPrice != nil {
		return *m.MinPrice
	}
	return 0
}

func (m *CodisUserProfileUid_PurPowInfo) GetMaxPrice() int32 {
	if m != nil && m.MaxPrice != nil {
		return *m.MaxPrice
	}
	return 0
}

func init() {
	proto.RegisterType((*CodisUserProfileUid)(nil), "CodisUserProfileUid")
	proto.RegisterType((*CodisUserProfileUid_SigCarMessage)(nil), "CodisUserProfileUid.SigCarMessage")
	proto.RegisterType((*CodisUserProfileUid_PurPowInfo)(nil), "CodisUserProfileUid.PurPowInfo")
}

func init() { proto.RegisterFile("main.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0x49, 0xb7, 0x79, 0xd3, 0x4e, 0x79, 0x69, 0xdd, 0x1e, 0x5c, 0xea, 0xc1, 0xd8, 0x53,
	0x4e, 0xa5, 0xd4, 0x4f, 0xa0, 0x05, 0x21, 0x60, 0x21, 0x50, 0x72, 0xf0, 0x14, 0x42, 0x76, 0x53,
	0x57, 0x34, 0x5b, 0x66, 0x36, 0x6a, 0x4f, 0x7e, 0x4d, 0x3f, 0x8e, 0x64, 0x93, 0xfa, 0x07, 0x7a,
	0xfd, 0x3d, 0xcf, 0x3c, 0xf3, 0xcc, 0xc0, 0xd5, 0xda, 0x48, 0x4d, 0x29, 0x29, 0x4c, 0xd0, 0x94,
	0xfa, 0x59, 0xa5, 0x5a, 0x66, 0x1b, 0x45, 0x94, 0xef, 0xd4, 0x62, 0x8f, 0xc6, 0x9a, 0xf9, 0x27,
	0x83, 0xe9, 0x09, 0x17, 0x9f, 0xc0, 0x60, 0x6d, 0x49, 0xa1, 0x56, 0x24, 0xbc, 0x90, 0x45, 0x7e,
	0x4b, 0x4a, 0x83, 0xf5, 0x0b, 0x89, 0xde, 0x91, 0xdc, 0x52, 0x47, 0x98, 0x23, 0xd7, 0x10, 0xc4,
	0xb2, 0x2c, 0x72, 0x24, 0xd1, 0x0f, 0x59, 0x34, 0x5a, 0xcd, 0x17, 0x27, 0xc2, 0x17, 0x5b, 0xbd,
	0x5b, 0xe7, 0xd8, 0x15, 0xe1, 0x1c, 0x20, 0x31, 0xa8, 0xba, 0x20, 0xdf, 0x05, 0x2d, 0x21, 0x48,
	0x93, 0x1a, 0x13, 0xf3, 0x26, 0xfe, 0x85, 0x5e, 0x34, 0x5a, 0x5d, 0x9e, 0x0c, 0x6a, 0x2d, 0x71,
	0x55, 0x1a, 0x3e, 0x03, 0x1e, 0x57, 0x56, 0xa1, 0x22, 0xbb, 0x75, 0xb5, 0xef, 0x35, 0x59, 0x11,
	0xb8, 0xb4, 0x11, 0xb0, 0x54, 0x4b, 0x31, 0x08, 0xbd, 0x68, 0xc8, 0xcf, 0x61, 0x7c, 0x34, 0xde,
	0xd4, 0xf6, 0xd1, 0x20, 0x89, 0x61, 0xc8, 0x22, 0xc6, 0x2f, 0x60, 0x7a, 0x14, 0x1e, 0x4c, 0xfd,
	0xa4, 0x5b, 0x55, 0x40, 0x23, 0xce, 0x3e, 0xe0, 0xff, 0xdf, 0xd6, 0x63, 0x08, 0xb6, 0x7b, 0x55,
	0x64, 0x5a, 0x0a, 0x2f, 0xf4, 0xba, 0x6f, 0x60, 0x5e, 0xc9, 0x86, 0xf4, 0x1c, 0xe1, 0x00, 0x77,
	0x79, 0x61, 0x0d, 0x1e, 0x1a, 0xc6, 0xbe, 0x5d, 0xf5, 0x21, 0x93, 0xb9, 0x55, 0xa2, 0xef, 0xfa,
	0x70, 0x80, 0x98, 0x32, 0x89, 0xfa, 0x55, 0x57, 0x3b, 0xe1, 0x3b, 0xd7, 0x19, 0x0c, 0xdb, 0x23,
	0x9a, 0xc1, 0xe6, 0x01, 0xfe, 0x6c, 0x09, 0xf0, 0xeb, 0xda, 0x09, 0x0c, 0x36, 0xba, 0x4a, 0x50,
	0x17, 0xea, 0x67, 0xfd, 0x26, 0x7f, 0x6f, 0x89, 0x5b, 0xff, 0x15, 0x00, 0x00, 0xff, 0xff, 0x56,
	0x91, 0x4e, 0x5e, 0xfe, 0x01, 0x00, 0x00,
}
