
DROP TABLE `tb_awesome`;

CREATE TABLE IF NOT EXISTS `tb_awesome`(
   `id` INT UNSIGNED AUTO_INCREMENT COMMENT '自增ID',
   `title` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '标题',
   `author` VARCHAR(40) NOT NULL DEFAULT '' COMMENT '作者',
	 `id_delete`  TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已删除',
	 `create_user` VARCHAR(40) NOT NULL DEFAULT 'admin' COMMENT '创建者',
   `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	 `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	 `delete_time` TIMESTAMP NOT NULL DEFAULT '2017-07-30 15:00:01' COMMENT '删除时间',
   PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;